import dotenv from "dotenv";
dotenv.config();

const PORT=process.env.PORT;
const MONGODB_URL=process.env.MONGODB_URL;

const CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_NAME=process.env.CLOUDINARY_NAME;

const PRIVATE_KEY_TOKEN=process.env.PRIVATE_KEY_TOKEN;
const EXPIRY_TOKEN=process.env.EXPIRY_TOKEN;

const ADMIN_EMAIL=process.env.ADMIN_EMAIL;
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;
const ADMIN_PRIVATE_KEY_TOKEN=process.env.ADMIN_PRIVATE_KEY_TOKEN

const ROJARPAY_API_KEY=process.env.ROJARPAY_API_KEY;
const ROJARPAY_KEY_SECRET=process.env.ROJARPAY_KEY_SECRET;



export {ROJARPAY_API_KEY,ROJARPAY_KEY_SECRET,PORT,MONGODB_URL,CLOUDINARY_NAME,CLOUDINARY_API_SECRET,CLOUDINARY_API_KEY,PRIVATE_KEY_TOKEN,EXPIRY_TOKEN,ADMIN_PASSWORD,ADMIN_EMAIL,ADMIN_PRIVATE_KEY_TOKEN};
